# docker-compose -f docker-compose.production.yml up --build --force-recreate
version: '3'

services:
  app:
    image: docker-nextjs
    build:
      context: .
      dockerfile: Dockerfile.production
    ports: 
      - 3000:3000