import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { getSortedPostsData, PostData } from '../lib/posts';

type Props = {
  allPostsData: PostData[];
};

const Home: NextPage<Props> = ({ allPostsData }: Props) => (
  <div className="mx-auto">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="flex flex-col items-center justify-center min-h-screen px-5">
      <h1 className="text-4xl">
        Learn <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p className="my-16 text-lg">
        Get started by editing <code className="p-3 rounded bg-slate-100/50">pages/index.tsx</code>
      </p>

      <div className="grid grid-flow-col gap-8 auto-cols-fr">
        <Link href="/posts/first-post">
          <a className="p-4 border rounded hover:text-blue-600 hover:border-blue-600" rel="noopener noreferrer">
            <h2>First Post &rarr;</h2>
            <p>Read the awesome first post!</p>
          </a>
        </Link>
        {allPostsData.map(({ id, date, title }) => (
          <Link href={`/posts/${id}`} key={id}>
            <a className="p-4 border rounded hover:text-blue-600 hover:border-blue-600" rel="noopener noreferrer">
              <h2>{title} &rarr;</h2>
              <p>{date}</p>
            </a>
          </Link>
        ))}
      </div>
    </main>

    <footer className="flex items-center justify-center flex-grow px-5 py-8 border-t">
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className="h-4">
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
);

export default Home;

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}
